inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Max: 120
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AssignmentInCondition:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/MultilineBlockChain:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%w': ()
