inherit_from:
  - ../.rubocop.yml

require: rubocop-rspec


Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/NotToNot:
  EnforcedStyle: to_not


Style/BlockDelimiters:
  Enabled: false
